ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS depth integer DEFAULT 1 NOT NULL;

ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS parent_id bigint;

ALTER TABLE IF EXISTS study_folder
    ADD CONSTRAINT IF NOT EXISTS fk_study_folder_parent
    FOREIGN KEY (parent_id) REFERENCES study_folder(id);

ALTER TABLE IF EXISTS study_file
    ADD COLUMN IF NOT EXISTS knowledge_enabled boolean DEFAULT true NOT NULL;

ALTER TABLE IF EXISTS user_ai_settings
    ADD COLUMN IF NOT EXISTS presets_json TEXT;

UPDATE study_file
SET knowledge_enabled = true
WHERE knowledge_enabled IS NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS page_number integer DEFAULT 1 NOT NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS chunking_version integer DEFAULT 1 NOT NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS correct_hit_count integer DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS wrong_hit_count integer DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS cite_count integer DEFAULT 0 NOT NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS last_accessed_at timestamp with time zone;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS last_practiced_at timestamp with time zone;

CREATE TABLE IF NOT EXISTS knowledge_chunk_event (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    chunk_id bigint not null,
    file_id bigint not null,
    folder_id bigint not null,
    event_type varchar(32) not null,
    correct boolean,
    created_at timestamp with time zone not null
);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_event_owner_created
    ON knowledge_chunk_event(owner_id, created_at);

CREATE INDEX IF NOT EXISTS idx_knowledge_chunk_event_chunk
    ON knowledge_chunk_event(chunk_id);

CREATE TABLE IF NOT EXISTS mistake_practice_event (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    mistake_id bigint not null,
    correct boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone not null
);

CREATE INDEX IF NOT EXISTS idx_mistake_practice_event_owner_created
    ON mistake_practice_event(owner_id, created_at);

ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS subject_folder boolean DEFAULT false NOT NULL;

ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS subject_order integer DEFAULT 0 NOT NULL;

CREATE TABLE IF NOT EXISTS user_study_profile (
    id bigint generated by default as identity primary key,
    owner_id bigint not null unique,
    exam_date date,
    onboarded boolean DEFAULT false NOT NULL,
    subject_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_original_name varchar(180);

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_stored_path varchar(255);

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_content_type varchar(120);

CREATE TABLE IF NOT EXISTS mistake_attachment (
    id bigint generated by default as identity primary key,
    mistake_id bigint not null,
    type varchar(24) not null,
    original_name varchar(180) not null,
    display_name varchar(180) not null,
    stored_path varchar(255) not null,
    content_type varchar(120) not null,
    created_at timestamp with time zone not null
);

CREATE TABLE IF NOT EXISTS mistake_subject_tag (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    name varchar(60) not null,
    created_at timestamp with time zone not null
);

CREATE TABLE IF NOT EXISTS mistake_question_subject_tag (
    mistake_id bigint not null,
    subject_tag_id bigint not null,
    primary key (mistake_id, subject_tag_id)
);

CREATE TABLE IF NOT EXISTS mistake_question_chunk (
    id bigint generated by default as identity primary key,
    mistake_id bigint not null,
    chunk_id bigint not null,
    source_type varchar(24) not null,
    created_at timestamp with time zone not null
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_mistake_question_chunk
    ON mistake_question_chunk(mistake_id, chunk_id);

CREATE TABLE IF NOT EXISTS study_plan_item (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    title varchar(120) not null,
    subject varchar(120),
    description varchar(800),
    item_type varchar(24) not null,
    start_date date not null,
    start_time time not null,
    end_time time not null,
    location varchar(120),
    priority varchar(16) not null,
    status varchar(16) not null,
    source varchar(16) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

CREATE INDEX IF NOT EXISTS idx_study_plan_owner_date
    ON study_plan_item(owner_id, start_date);

CREATE INDEX IF NOT EXISTS idx_study_plan_owner_status
    ON study_plan_item(owner_id, status);
