ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS depth integer DEFAULT 1 NOT NULL;

ALTER TABLE IF EXISTS study_folder
    ADD COLUMN IF NOT EXISTS parent_id bigint;

ALTER TABLE IF EXISTS study_folder
    ADD CONSTRAINT IF NOT EXISTS fk_study_folder_parent
    FOREIGN KEY (parent_id) REFERENCES study_folder(id);

ALTER TABLE IF EXISTS study_file
    ADD COLUMN IF NOT EXISTS knowledge_enabled boolean DEFAULT true NOT NULL;

UPDATE study_file
SET knowledge_enabled = true
WHERE knowledge_enabled IS NULL;

ALTER TABLE IF EXISTS knowledge_chunk
    ADD COLUMN IF NOT EXISTS page_number integer DEFAULT 1 NOT NULL;

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_original_name varchar(180);

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_stored_path varchar(255);

ALTER TABLE IF EXISTS mistake_question
    ADD COLUMN IF NOT EXISTS question_content_type varchar(120);

CREATE TABLE IF NOT EXISTS mistake_attachment (
    id bigint generated by default as identity primary key,
    mistake_id bigint not null,
    type varchar(24) not null,
    original_name varchar(180) not null,
    display_name varchar(180) not null,
    stored_path varchar(255) not null,
    content_type varchar(120) not null,
    created_at timestamp with time zone not null
);

CREATE TABLE IF NOT EXISTS mistake_subject_tag (
    id bigint generated by default as identity primary key,
    owner_id bigint not null,
    name varchar(60) not null,
    created_at timestamp with time zone not null
);

CREATE TABLE IF NOT EXISTS mistake_question_subject_tag (
    mistake_id bigint not null,
    subject_tag_id bigint not null,
    primary key (mistake_id, subject_tag_id)
);
